services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: airpulse-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      - airpulse-network

  backend:
    build:
      context: .
    image: airpulse-backend
    container_name: airpulse-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - timescaledb
    networks:
      - airpulse-network

volumes:
  timescaledb-data:

networks:
  airpulse-network:
    driver: bridge